ALTER TABLE meeting_links
  ADD COLUMN topic VARCHAR(200) NOT NULL DEFAULT 'Wellness Session',
  ADD COLUMN meeting_date VARCHAR(80) NOT NULL DEFAULT '',
  ADD COLUMN meeting_time VARCHAR(80) NOT NULL DEFAULT '',
  ADD COLUMN meeting_id VARCHAR(80) NOT NULL DEFAULT '',
  ADD COLUMN passcode VARCHAR(100) NOT NULL DEFAULT '';
